name: setup-react
on: push   
jobs:   
  app-react:  
    runs-on: ubuntu-latest 
    steps: 
    - name: Code Checkout
      uses: actions/checkout@v4 
    - name: Install nodejs
      uses: actions/setup-node@v4
      with: 
        node-version: '20'
    - name: Install Dependencies   
      run: npm ci 
    - name: Deploy 
      run: echo "Deploy successful"
  
  second-job:
    runs-on: ubuntu-latest 
    steps:
    - name: Code Checkout 
      uses: actions/checkout@v4 
    - name: Install Apache2 
      run: sudo apt update && sudo apt install apache2 -y 
    - name: List Directory Structure 
      run: ls -l /
    needs:
      app-react
